version: '3.8'

services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - ./:/usr/app 
    depends_on:
      - mysql   
    ports:
      - "3000:3000"
    command: nest start --watch
